---
title: "Data Exploration & Visualization"
author: "Caroline Newell"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load Libraries
library(tidyverse)
library(readr)

#Load Data
SMFS_OTR_Thesis_WithZeros_WithZeros <- read_csv("Data/SMFS_OTR_Thesis_WithZeros_WithZeros.csv")
```

```{r}
# Create the catch frequency graph
#WaterTemp Graph for Tule Perch 2011-2023
glimpse(SMFS_OTR_Thesis_WithZeros_WithZeros.csv)
#dev.off()

SMFS_OTR_Thesis_WithZeros_WithZeros %>% 
  filter(OrganismCode %in% "TP") %>% 
  ggplot(aes(x = WaterTemperature, y = Count)) +
  geom_col(position = "dodge") +
  labs(x = "Water Temp", y = "Catch Frequency", title = "Tule Perch Catch Frequency by Water Temp") +
  theme_minimal() 

```

```{r}

CatchFrequency <- function(data, x, y, title) {
  ggplot(data) +
    aes({{x}}, {{y}}) +
    geom_col(position = "dodge") +
    labs(x = deparse(substitute(x)), y = deparse(substitute(y)), title = title) +
    theme_minimal()
} #deparse automatically pulls the name from x and y to label the axes. This function is to make plotting more streamlined :)

#Water Temp graph for TP 2011-2023
WT.Plot<-SMFS_OTR_Thesis_WithZeros_WithZeros %>% 
  filter(OrganismCode %in% "TP", !is.na(WaterTemperature), !is.na(Count)) %>%
  CatchFrequency(WaterTemperature, Count, title = "TP & Water Temp SMFS 2011-2023")
#DO Graph for TP  2011-2023
DO.Plot<-SMFS_OTR_Thesis_WithZeros_WithZeros %>% 
  filter(OrganismCode %in% "TP", !is.na(DO), !is.na(Count)) %>%
  CatchFrequency(DO, Count, title = "TP & DO SMFS 2011-2023")
#Salinity Graph for TP 2011-2023
PPT.Plot<-SMFS_OTR_Thesis_WithZeros_WithZeros %>% 
  filter(OrganismCode %in% "TP", !is.na(Salinity), !is.na(Count)) %>%
  CatchFrequency(Salinity, Count, title = "TP & Salinity SMFS 2011-2023")
#Secchi Graph for TP 2011-2023
Secchi.Plot<-SMFS_OTR_Thesis_WithZeros_WithZeros %>% 
  filter(OrganismCode %in% "TP", !is.na(Secchi), !is.na(Count)) %>%
  CatchFrequency(Secchi, Count, title = "TP & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for Striped Bass 2011-2023
WT.Plot<-SMFS_OTR_Thesis_WithZeros_WithZeros %>% 
  filter(OrganismCode %in% "SB", !is.na(WaterTemperature), !is.na(Count)) %>%
  CatchFrequency(WaterTemperature, Count, title = "SB & Water Temp SMFS 2011-2023")
#DO Graph for SB  2011-2023
DO.Plot<-SMFS_OTR_Thesis_WithZeros_WithZeros %>% 
  filter(OrganismCode %in% "SB", !is.na(DO), !is.na(Count)) %>%
  CatchFrequency(DO, Count, title = "SB & DO SMFS 2011-2023")
#Salinity Graph for SB 2011-2023
PPT.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "SB", !is.na(Salinity), !is.na(Count)) %>%
  CatchFrequency(Salinity, Count, title = "SB & Salinity SMFS 2011-2023")
#Secchi Graph for SB 2011-2023
Secchi.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "SB", !is.na(Secchi), !is.na(Count)) %>%
  CatchFrequency(Secchi, Count, title = "SB & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for Prickly Sculpin 2011-2023
WT.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "SCP", !is.na(WaterTemperature), !is.na(Count)) %>%
  CatchFrequency(WaterTemperature, Count, title = "SCP & Water Temp SMFS 2011-2023")
#DO Graph for SCP  2011-2023
DO.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "SCP", !is.na(DO), !is.na(Count)) %>%
  CatchFrequency(DO, Count, title = "SCP & DO SMFS 2011-2023")
#Salinity Graph for SCP 2011-2023
PPT.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "SCP", !is.na(Salinity), !is.na(Count)) %>%
  CatchFrequency(Salinity, Count, title = "SCP & Salinity SMFS 2011-2023")
#Secchi Graph for SCP 2011-2023
Secchi.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "SCP", !is.na(Secchi), !is.na(Count)) %>%
  CatchFrequency(Secchi, Count, title = "SCP & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for Longfin Smelt 2011-2023
WT.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "LFS", !is.na(WaterTemperature), !is.na(Count)) %>%
  CatchFrequency(WaterTemperature, Count, title = "LFS & Water Temp SMFS 2011-2023")
#DO Graph for LFS  2011-2023
DO.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "LFS", !is.na(DO), !is.na(Count)) %>%
  CatchFrequency(DO, Count, title = "LFS & DO SMFS 2011-2023")
#Salinity Graph for LFS 2011-2023
PPT.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "LFS", !is.na(Salinity), !is.na(Count)) %>%
  CatchFrequency(Salinity, Count, title = "LFS & Salinity SMFS 2011-2023")
#Secchi Graph for LFS 2011-2023
Secchi.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "LFS", !is.na(Secchi), !is.na(Count)) %>%
  CatchFrequency(Secchi, Count, title = "LFS & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for Yellowfin Goby 2011-2023
WT.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "YFG", !is.na(WaterTemperature), !is.na(Count)) %>%
  CatchFrequency(WaterTemperature, Count, title = "YFG & Water Temp SMFS 2011-2023")
#DO Graph for YFG  2011-2023
DO.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "YFG", !is.na(DO), !is.na(Count)) %>%
  CatchFrequency(DO, Count, title = "YFG & DO SMFS 2011-2023")
#Salinity Graph for YFG 2011-2023
PPT.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "YFG", !is.na(Salinity), !is.na(Count)) %>%
  CatchFrequency(Salinity, Count, title = "YFG & Salinity SMFS 2011-2023")
#Secchi Graph for YFG 2011-2023
Secchi.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "YFG", !is.na(Secchi), !is.na(Count)) %>%
  CatchFrequency(Secchi, Count, title = "YFG & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for American Shad 2011-2023
WT.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "ASH", !is.na(WaterTemperature), !is.na(Count)) %>%
  CatchFrequency(WaterTemperature, Count, title = "ASH & Water Temp SMFS 2011-2023")
#DO Graph for ASH  2011-2023
DO.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "ASH", !is.na(DO), !is.na(Count)) %>%
  CatchFrequency(DO, Count, title = "ASH & DO SMFS 2011-2023")
#Salinity Graph for ASH 2011-2023
PPT.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "ASH", !is.na(Salinity), !is.na(Count)) %>%
  CatchFrequency(Salinity, Count, title = "ASH & Salinity SMFS 2011-2023")
#Secchi Graph for ASH 2011-2023
Secchi.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "ASH", !is.na(Secchi), !is.na(Count)) %>%
  CatchFrequency(Secchi, Count, title = "ASH & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for Threadfin Shad 2011-2023
WT.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "TFS", !is.na(WaterTemperature), !is.na(Count)) %>%
  CatchFrequency(WaterTemperature, Count, title = "TFS & Water Temp SMFS 2011-2023")
#DO Graph for TFS  2011-2023
DO.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "TFS", !is.na(DO), !is.na(Count)) %>%
  CatchFrequency(DO, Count, title = "TFS & DO SMFS 2011-2023")
#Salinity Graph for TFS 2011-2023
PPT.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "TFS", !is.na(Salinity), !is.na(Count)) %>%
  CatchFrequency(Salinity, Count, title = "TFS & Salinity SMFS 2011-2023")
#Secchi Graph for TFS 2011-2023
Secchi.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "TFS", !is.na(Secchi), !is.na(Count)) %>%
  CatchFrequency(Secchi, Count, title = "TFS & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for Starry Flounder 2011-2023
WT.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "SF", !is.na(WaterTemperature), !is.na(Count)) %>%
  CatchFrequency(WaterTemperature, Count, title = "SF & Water Temp SMFS 2011-2023")
#DO Graph for SF  2011-2023
DO.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "SF", !is.na(DO), !is.na(Count)) %>%
  CatchFrequency(DO, Count, title = "SF & DO SMFS 2011-2023")
#Salinity Graph for SF 2011-2023
PPT.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "SF", !is.na(Salinity), !is.na(Count)) %>%
  CatchFrequency(Salinity, Count, title = "SF & Salinity SMFS 2011-2023")
#Secchi Graph for SF 2011-2023
Secchi.Plot<-SMFS_OTR_Thesis_WithZeros %>% 
  filter(OrganismCode %in% "SF", !is.na(Secchi), !is.na(Count)) %>%
  CatchFrequency(Secchi, Count, title = "SF & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")


```

```{r}


#Lets plot WaterTemp CPUE now
# Step 1: Sum count over each unique sample row ID
summed_data <- SMFS_OTR_Thesis_WithZeros_WithZeros %>%
  group_by(SampleRowID, OrganismCode, WaterTemperature) %>%
  summarize(SumCount = sum(Count),
            n=n(SampleRowID),
            CPUE = SumCount/n())

# Step 2: Calculate catch per unit effort
#I want CPUE for each water quality parameter

#CPUE = catch per 5 minute trawl (filter out durations outside of norm) (so could split 10 min trawl catch in half or calculate them separately). For now. 
#Use SampleRowID as unique trawls. Columns: SampleRowID, Metadata, OrganismCode, Count (size will come later), Site.

CPUE_5min_Temp <- SMFS_OTR_Thesis_WithZeros_WithZeros %>% filter(TowDuration == 5) %>% group_by(WaterTemperature, OrganismCode) %>% summarize(CPUE = sum(Count)/n(), n = n(), Count = Count)

CPUE_10min_Temp <- SMFS_OTR_Thesis_WithZeros_WithZeros %>% filter(TowDuration == 10) %>% group_by(WaterTemperature, OrganismCode) %>% summarize(CPUE = sum(Count)/n(), n = n(), Count = Count)


#Lets run a check real quick
#Removing NAs from Tow Duration since we won't have CPUE from them
SMFS_OTR_Thesis_WithZeros_WithZeros_NoTowNA<-SMFS_OTR_Thesis_WithZeros_WithZeros %>% filter(!is.na(TowDuration)) #333872

Five<-SMFS_OTR_Thesis_WithZeros_WithZeros_NoTowNA %>% filter(TowDuration == 5) #237628, so matches the CPUE calculation
Ten<-SMFS_OTR_Thesis_WithZeros_WithZeros_NoTowNA %>% filter(TowDuration == 10) #93027, matches CPUE calculation
Other<-SMFS_OTR_Thesis_WithZeros_WithZeros_NoTowNA %>% filter(TowDuration != 5, 
                                                    TowDuration != 10) #3217
3217+237628+93027 #checks out!

CPUE_5min_DO <- SMFS_OTR_Thesis_WithZeros_WithZeros %>% filter(TowDuration == 5) %>% group_by(DO, OrganismCode) %>% summarize(CPUE = sum(Count)/n(), n = n(), Count = Count)

CPUE_10min_DO <- SMFS_OTR_Thesis_WithZeros_WithZeros %>% filter(TowDuration == 10) %>% group_by(DO, OrganismCode) %>% summarize(CPUE = sum(Count)/n(), n = n(), Count = Count)

CPUE_5min_PPT <- SMFS_OTR_Thesis_WithZeros_WithZeros %>% filter(TowDuration == 5) %>% group_by(Salinity, OrganismCode) %>% summarize(CPUE = sum(Count)/n(), n = n(), Count = Count)

CPUE_10min_PPT <- SMFS_OTR_Thesis_WithZeros_WithZeros %>% filter(TowDuration == 10) %>% group_by(Salinity, OrganismCode) %>% summarize(CPUE = sum(Count)/n(), n = n(), Count = Count)

CPUE_5min_Secchi <- SMFS_OTR_Thesis_WithZeros_WithZeros %>% filter(TowDuration == 5) %>% group_by(Secchi, OrganismCode) %>% summarize(CPUE = sum(Count)/n(), n = n(), Count = Count)

CPUE_10min_Secchi <- SMFS_OTR_Thesis_WithZeros_WithZeros %>% filter(TowDuration == 10) %>% group_by(Secchi, OrganismCode) %>% summarize(CPUE = sum(Count)/n(), n = n(), Count = Count)

#Plot CPUE Now
CatchFrequency <- function(data, x, y, title) {
  ggplot(data) +
    aes({{x}}, {{y}}) +
    geom_col(position = "dodge") +
    labs(x = deparse(substitute(x)), y = deparse(substitute(y)), title = title) +
    theme_minimal() + scale_x_continuous(breaks = seq(0, 1000, 5)) + scale_y_continuous(breaks = seq(0, 50, 1))
}
#Water Temp graph for TP 2011-2023
WT.Plot<-CPUE_5min_Temp %>% 
  filter(OrganismCode %in% "TP", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "5 min Trawl Catch per Trawl of TP & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for TP  2011-2023
DO.Plot<-CPUE_5min_DO %>% 
  filter(OrganismCode %in% "TP", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "5 min Trawl Catch per Trawl of TP & DO SMFS 2011-2023")
#Salinity Graph for TP 2011-2023
PPT.Plot<-CPUE_5min_PPT %>% 
  filter(OrganismCode %in% "TP", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "5 min Trawl Catch per Trawl of TP & Salinity SMFS 2011-2023")
#Secchi Graph for TP 2011-2023
Secchi.Plot<-CPUE_5min_Secchi %>% 
  filter(OrganismCode %in% "TP", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "5 min Trawl Catch per Trawl of TP & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for TP 2011-2023
WT.Plot<-CPUE_10min_Temp %>% 
  filter(OrganismCode %in% "TP", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "10 min Trawl Catch per Trawl of TP & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for TP  2011-2023
DO.Plot<-CPUE_10min_DO %>% 
  filter(OrganismCode %in% "TP", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "10 min Trawl Catch per Trawl of TP & DO SMFS 2011-2023")
#Salinity Graph for TP 2011-2023
PPT.Plot<-CPUE_10min_PPT %>% 
  filter(OrganismCode %in% "TP", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "10 min Trawl Catch per Trawl of TP & Salinity SMFS 2011-2023")
#Secchi Graph for TP 2011-2023
Secchi.Plot<-CPUE_10min_Secchi %>% 
  filter(OrganismCode %in% "TP", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "10 min Trawl Catch per Trawl of TP & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")




#Water Temp CPUE graph for SB 2011-2023
WT.Plot<-CPUE_5min_Temp %>% 
  filter(OrganismCode %in% "SB", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "5 min Trawl Catch per Trawl of SB & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for SB  2011-2023
DO.Plot<-CPUE_5min_DO %>% 
  filter(OrganismCode %in% "SB", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "5 min Trawl Catch per Trawl of SB & DO SMFS 2011-2023")
#Salinity Graph for SB 2011-2023
PPT.Plot<-CPUE_5min_PPT %>% 
  filter(OrganismCode %in% "SB", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "5 min Trawl Catch per Trawl of SB & Salinity SMFS 2011-2023")
#Secchi Graph for SB 2011-2023
Secchi.Plot<-CPUE_5min_Secchi %>% 
  filter(OrganismCode %in% "SB", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "5 min Trawl Catch per Trawl of SB & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for SB 2011-2023
WT.Plot<-CPUE_10min_Temp %>% 
  filter(OrganismCode %in% "SB", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "10 min Trawl Catch per Trawl of SB & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for SB  2011-2023
DO.Plot<-CPUE_10min_DO %>% 
  filter(OrganismCode %in% "SB", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "10 min Trawl Catch per Trawl of SB & DO SMFS 2011-2023")
#Salinity Graph for SB 2011-2023
PPT.Plot<-CPUE_10min_PPT %>% 
  filter(OrganismCode %in% "SB", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "10 min Trawl Catch per Trawl of SB & Salinity SMFS 2011-2023")
#Secchi Graph for SB 2011-2023
Secchi.Plot<-CPUE_10min_Secchi %>% 
  filter(OrganismCode %in% "SB", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "10 min Trawl Catch per Trawl of SB & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")






#Water Temp CPUE graph for SCP 2011-2023
WT.Plot<-CPUE_5min_Temp %>% 
  filter(OrganismCode %in% "SCP", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "5 min Trawl Catch per Trawl of SCP & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for SCP  2011-2023
DO.Plot<-CPUE_5min_DO %>% 
  filter(OrganismCode %in% "SCP", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "5 min Trawl Catch per Trawl of SCP & DO SMFS 2011-2023")
#Salinity Graph for SCP 2011-2023
PPT.Plot<-CPUE_5min_PPT %>% 
  filter(OrganismCode %in% "SCP", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "5 min Trawl Catch per Trawl of SCP & Salinity SMFS 2011-2023")
#Secchi Graph for SCP 2011-2023
Secchi.Plot<-CPUE_5min_Secchi %>% 
  filter(OrganismCode %in% "SCP", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "5 min Trawl Catch per Trawl of SCP & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for SCP 2011-2023
WT.Plot<-CPUE_10min_Temp %>% 
  filter(OrganismCode %in% "SCP", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "10 min Trawl Catch per Trawl of SCP & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for SCP  2011-2023
DO.Plot<-CPUE_10min_DO %>% 
  filter(OrganismCode %in% "SCP", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "10 min Trawl Catch per Trawl of SCP & DO SMFS 2011-2023")
#Salinity Graph for SCP 2011-2023
PPT.Plot<-CPUE_10min_PPT %>% 
  filter(OrganismCode %in% "SCP", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "10 min Trawl Catch per Trawl of SCP & Salinity SMFS 2011-2023")
#Secchi Graph for SCP 2011-2023
Secchi.Plot<-CPUE_10min_Secchi %>% 
  filter(OrganismCode %in% "SCP", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "10 min Trawl Catch per Trawl of SCP & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")







#Water Temp CPUE graph for LFS 2011-2023
WT.Plot<-CPUE_5min_Temp %>% 
  filter(OrganismCode %in% "LFS", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "5 min Trawl Catch per Trawl of LFS & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for LFS  2011-2023
DO.Plot<-CPUE_5min_DO %>% 
  filter(OrganismCode %in% "LFS", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "5 min Trawl Catch per Trawl of LFS & DO SMFS 2011-2023")
#Salinity Graph for LFS 2011-2023
PPT.Plot<-CPUE_5min_PPT %>% 
  filter(OrganismCode %in% "LFS", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "5 min Trawl Catch per Trawl of LFS & Salinity SMFS 2011-2023")
#Secchi Graph for LFS 2011-2023
Secchi.Plot<-CPUE_5min_Secchi %>% 
  filter(OrganismCode %in% "LFS", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "5 min Trawl Catch per Trawl of LFS & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for LFS 2011-2023
WT.Plot<-CPUE_10min_Temp %>% 
  filter(OrganismCode %in% "LFS", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "10 min Trawl Catch per Trawl of LFS & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for LFS  2011-2023
DO.Plot<-CPUE_10min_DO %>% 
  filter(OrganismCode %in% "LFS", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "10 min Trawl Catch per Trawl of LFS & DO SMFS 2011-2023")
#Salinity Graph for LFS 2011-2023
PPT.Plot<-CPUE_10min_PPT %>% 
  filter(OrganismCode %in% "LFS", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "10 min Trawl Catch per Trawl of LFS & Salinity SMFS 2011-2023")
#Secchi Graph for LFS 2011-2023
Secchi.Plot<-CPUE_10min_Secchi %>% 
  filter(OrganismCode %in% "LFS", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "10 min Trawl Catch per Trawl of LFS & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")












#Water Temp CPUE graph for YFG 2011-2023
WT.Plot<-CPUE_5min_Temp %>% 
  filter(OrganismCode %in% "YFG", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "5 min Trawl Catch per Trawl of YFG & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for YFG  2011-2023
DO.Plot<-CPUE_5min_DO %>% 
  filter(OrganismCode %in% "YFG", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "5 min Trawl Catch per Trawl of YFG & DO SMFS 2011-2023")
#Salinity Graph for YFG 2011-2023
PPT.Plot<-CPUE_5min_PPT %>% 
  filter(OrganismCode %in% "YFG", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "5 min Trawl Catch per Trawl of YFG & Salinity SMFS 2011-2023")
#Secchi Graph for YFG 2011-2023
Secchi.Plot<-CPUE_5min_Secchi %>% 
  filter(OrganismCode %in% "YFG", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "5 min Trawl Catch per Trawl of YFG & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for YFG 2011-2023
WT.Plot<-CPUE_10min_Temp %>% 
  filter(OrganismCode %in% "YFG", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "10 min Trawl Catch per Trawl of YFG & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for YFG  2011-2023
DO.Plot<-CPUE_10min_DO %>% 
  filter(OrganismCode %in% "YFG", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "10 min Trawl Catch per Trawl of YFG & DO SMFS 2011-2023")
#Salinity Graph for YFG 2011-2023
PPT.Plot<-CPUE_10min_PPT %>% 
  filter(OrganismCode %in% "YFG", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "10 min Trawl Catch per Trawl of YFG & Salinity SMFS 2011-2023")
#Secchi Graph for YFG 2011-2023
Secchi.Plot<-CPUE_10min_Secchi %>% 
  filter(OrganismCode %in% "YFG", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "10 min Trawl Catch per Trawl of YFG & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")









#Water Temp CPUE graph for ASH 2011-2023
WT.Plot<-CPUE_5min_Temp %>% 
  filter(OrganismCode %in% "ASH", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "5 min Trawl Catch per Trawl of ASH & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for ASH  2011-2023
DO.Plot<-CPUE_5min_DO %>% 
  filter(OrganismCode %in% "ASH", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "5 min Trawl Catch per Trawl of ASH & DO SMFS 2011-2023")
#Salinity Graph for ASH 2011-2023
PPT.Plot<-CPUE_5min_PPT %>% 
  filter(OrganismCode %in% "ASH", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "5 min Trawl Catch per Trawl of ASH & Salinity SMFS 2011-2023")
#Secchi Graph for ASH 2011-2023
Secchi.Plot<-CPUE_5min_Secchi %>% 
  filter(OrganismCode %in% "ASH", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "5 min Trawl Catch per Trawl of ASH & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for ASH 2011-2023
WT.Plot<-CPUE_10min_Temp %>% 
  filter(OrganismCode %in% "ASH", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "10 min Trawl Catch per Trawl of ASH & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for ASH  2011-2023
DO.Plot<-CPUE_10min_DO %>% 
  filter(OrganismCode %in% "ASH", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "10 min Trawl Catch per Trawl of ASH & DO SMFS 2011-2023")
#Salinity Graph for ASH 2011-2023
PPT.Plot<-CPUE_10min_PPT %>% 
  filter(OrganismCode %in% "ASH", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "10 min Trawl Catch per Trawl of ASH & Salinity SMFS 2011-2023")
#Secchi Graph for ASH 2011-2023
Secchi.Plot<-CPUE_10min_Secchi %>% 
  filter(OrganismCode %in% "ASH", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "10 min Trawl Catch per Trawl of ASH & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

NoNASecchi<-SMFS_OTR_Thesis_WithZeros_WithZeros_NoTowNA %>% filter(!is.na(Secchi))
range(NoNASecchi$Secchi) #Max secchi is 99! Catches over 99 are unmeasurable (possibly written as 99?) since we only bring out a meter stick.











#Water Temp CPUE graph for TFS 2011-2023
WT.Plot<-CPUE_5min_Temp %>% 
  filter(OrganismCode %in% "TFS", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "5 min Trawl Catch per Trawl of TFS & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for TFS  2011-2023
DO.Plot<-CPUE_5min_DO %>% 
  filter(OrganismCode %in% "TFS", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "5 min Trawl Catch per Trawl of TFS & DO SMFS 2011-2023")
#Salinity Graph for TFS 2011-2023
PPT.Plot<-CPUE_5min_PPT %>% 
  filter(OrganismCode %in% "TFS", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "5 min Trawl Catch per Trawl of TFS & Salinity SMFS 2011-2023")
#Secchi Graph for TFS 2011-2023
Secchi.Plot<-CPUE_5min_Secchi %>% 
  filter(OrganismCode %in% "TFS", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "5 min Trawl Catch per Trawl of TFS & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for TFS 2011-2023
WT.Plot<-CPUE_10min_Temp %>% 
  filter(OrganismCode %in% "TFS", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "10 min Trawl Catch per Trawl of TFS & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for TFS  2011-2023
DO.Plot<-CPUE_10min_DO %>% 
  filter(OrganismCode %in% "TFS", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "10 min Trawl Catch per Trawl of TFS & DO SMFS 2011-2023")
#Salinity Graph for TFS 2011-2023
PPT.Plot<-CPUE_10min_PPT %>% 
  filter(OrganismCode %in% "TFS", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "10 min Trawl Catch per Trawl of TFS & Salinity SMFS 2011-2023")
#Secchi Graph for TFS 2011-2023
Secchi.Plot<-CPUE_10min_Secchi %>% 
  filter(OrganismCode %in% "TFS", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "10 min Trawl Catch per Trawl of TFS & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")











#Water Temp CPUE graph for SF 2011-2023
WT.Plot<-CPUE_5min_Temp %>% 
  filter(OrganismCode %in% "SF", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "5 min Trawl Catch per Trawl of SF & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for SF  2011-2023
DO.Plot<-CPUE_5min_DO %>% 
  filter(OrganismCode %in% "SF", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "5 min Trawl Catch per Trawl of SF & DO SMFS 2011-2023")
#Salinity Graph for SF 2011-2023
PPT.Plot<-CPUE_5min_PPT %>% 
  filter(OrganismCode %in% "SF", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "5 min Trawl Catch per Trawl of SF & Salinity SMFS 2011-2023")
#Secchi Graph for SF 2011-2023
Secchi.Plot<-CPUE_5min_Secchi %>% 
  filter(OrganismCode %in% "SF", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "5 min Trawl Catch per Trawl of SF & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#Water Temp graph for SF 2011-2023
WT.Plot<-CPUE_10min_Temp %>% 
  filter(OrganismCode %in% "SF", !is.na(WaterTemperature)) %>%
  CatchFrequency(WaterTemperature, CPUE, title = "10 min Trawl Catch per Trawl of SF & Water Temp SMFS 2011-2023")
WT.Plot

#DO Graph for SF  2011-2023
DO.Plot<-CPUE_10min_DO %>% 
  filter(OrganismCode %in% "SF", !is.na(DO)) %>%
  CatchFrequency(DO, CPUE, title = "10 min Trawl Catch per Trawl of SF & DO SMFS 2011-2023")
#Salinity Graph for SF 2011-2023
PPT.Plot<-CPUE_10min_PPT %>% 
  filter(OrganismCode %in% "SF", !is.na(Salinity)) %>%
  CatchFrequency(Salinity, CPUE, title = "10 min Trawl Catch per Trawl of SF & Salinity SMFS 2011-2023")
#Secchi Graph for SF 2011-2023
Secchi.Plot<-CPUE_10min_Secchi %>% 
  filter(OrganismCode %in% "SF", !is.na(Secchi)) %>%
  CatchFrequency(Secchi, CPUE, title = "10 min Trawl Catch per Trawl of SF & Secchi SMFS 2011-2023")
# Arrange plots into a single image
plot_grid(WT.Plot, DO.Plot, PPT.Plot, Secchi.Plot, ncol = 2, labels = "AUTO")

#NEXT: Bin original dataframe (fewer rows but higher counts, column with Species_BinSize and do complete on that.)
glimpse(SMFS_OTR_Thesis_WithZeros_WithZeros)
glimpse(SMFS_AgesBySizeMo)

#Need to do this before adding zeros. New script!

```